---
# file: tasks/set-role-variables.yml
# set necessary role variables.
#

- name: Compose url for kibana downloading file, if necessary
  set_fact:
    kibana_tarball: kibana-{{ kibana_version }}-linux-x86_64
- name: compose url for downloading file, if necessary
  set_fact:
    kibana_tarball_url:  "{{ kibana_download_base_url }}/{{ kibana_tarball }}.tar.gz"

